[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 200

gas_reports = [
  "NaiveUserRegistry",
  "MediumUserRegistry",
  "OptimizedUserRegistry"
]
